#!/bin/sh
linter_exit_code=1
all_ts_files=$(git diff --cached --diff-filter=d --name-only | grep -E '.(jsx?|tsx?|astro)$')
./node_modules/.bin/eslint $all_ts_files --fix
linter_exit_code=$?
git add -f $all_ts_files
if [ $linter_exit_code -ne 0 ]
then
	echo ❌ Linting: Failed
  exit 1
else
	echo ✔ Linting: Passed
  exit 0
fi
